Lang = {
    ['app_title'] = "AV Cameras",
    ["camera_menu"] = "Cameras",
    ["all_cameras"] = "All Cameras",
    ["install"] = "~b~[E]~w~ Install",
    ["exit"] = "~b~[H]~w~ Exit",
    ["confirm"] = "~b~[E]~w~ Confirm",
    ['no_groups'] = "You don't have a cam group, register one using our APP",
    ['no_permission'] = "You don't have permission to do this.",
    ['player_not_found'] = "Player not found, wrong ID?",
    ['cant_share_yourself'] = "You can't share it with yourself",
    ['successfuly_shared'] = "Successfully shared",
    ['camara_removed'] = "Camara removed",
    ['not_vehicle'] = "You can't install the camera here",
    ['menu_title'] = "Register CamPro",
    ['cam_name'] = "Camera Name",
    ['cam_group'] = "Camera Group",
    ['no_access'] = "You don't have access to this command",
    ['vehicle_installed'] = "Camera installed",
    ['no_battery'] = "Can't access, the battery is low.",
    ['not_online'] = "The camera is not online, try again later.",
    ['vehicle_error'] = "You can't use this function while driving",
    ['no_cameras_nearby'] = "There's no security cameras nearby",
    ['camera_removed'] = "The vehicle camera got temporarily disabled",
    ['shared_group'] = "Shared With Me",
    ['restricted_camera'] = "You can't share this type of cameras",
    -- Camera Controls
    ['confirm_camera'] = "[E] Confirm",
    ['copy_coords'] = "[E] Copy Coords",
    ['cancel'] = "[H] Cancel",
    ['exit_vehicle'] = "[H] Exit",
    ['move_camera'] = "Arrow Keys - Move",
    ['rotate_camera'] = "Shift + Arrow Keys - Rotate",
    -- Camera signal
    ['interact'] = "[E] Interact",
    ['no_signal'] = "No signal available.",
    ['signal_found'] = "Signal detected...",
    ['distance'] = "meters",
    ['hacked'] = "You hacked the security system",
    ['fixed'] = "You fixed the security system",
    ['no_permission'] = "You can't do this right now",

}