RegisterNetEvent('av_meth:blip', function()
    local delivery = AddBlipForCoord(Config.BlipCoords[1], Config.BlipCoords[2], Config.BlipCoords[3])
    SetBlipSprite(delivery, Config.BlipIcon)
    SetBlipScale(delivery, Config.BlipScale)
    SetBlipDisplay(delivery, 4)
    SetBlipColour(delivery, Config.BlipColor)
    SetBlipAsShortRange(delivery, true)
    BeginTextCommandSetBlipName("STRING")
    AddTextComponentString(Lang['blip_text'])
    EndTextCommandSetBlipName(delivery)
end)