RegisterNetEvent('jobcenter:waypoint:garbage')
AddEventHandler('jobcenter:waypoint:garbage', function()
    SetNewWaypoint(-321.77, -1545.84)
end)

RegisterNetEvent('jobcenter:waypoint:taxi')
AddEventHandler('jobcenter:waypoint:taxi', function()
    SetNewWaypoint(907.84, -174.8)
end)

RegisterNetEvent('jobcenter:waypoint:trucker')
AddEventHandler('jobcenter:waypoint:trucker', function()
    SetNewWaypoint(1204.15, -3109.78)
end)

RegisterNetEvent('jobcenter:waypoint:logger')
AddEventHandler('jobcenter:waypoint:logger', function()
    SetNewWaypoint(-558.68, 5380.19)
end)

RegisterNetEvent('jobcenter:waypoint:mining')
AddEventHandler('jobcenter:waypoint:mining', function()
    SetNewWaypoint(2961.24, 2753.61)
end)
RegisterNetEvent('jobcenter:waypoint:postal')
AddEventHandler('jobcenter:waypoint:postal', function()
    SetNewWaypoint(-429.14, -2783.38)
end)